version: "3.2"

services:

  gisa-planos:
    image: gisa-planos:0.0.1
    container_name: gisa-planos
    restart: always
    depends_on:
      - gisa-db
    ports:
      - "8080:8080"
    networks:
      - apps-network

  gisa-auth:
    image: gisa-auth:0.0.1
    container_name: gisa-auth
    restart: always
    ports:
      - "8081:8081"
    networks:
      - apps-network
    depends_on:
      - gisa-db

  gisa-agenda-1:
    image: gisa-agenda:0.0.1
    container_name: gisa-agenda-1
    restart: always
    ports:
      - "8082:8082"
    networks:
      - apps-network
    depends_on:
      - gisa-db

  gisa-agenda-2:
    image: gisa-agenda:0.0.1
    container_name: gisa-agenda-2
    restart: always
    ports:
      - "8084:8082"
    networks:
      - apps-network
    depends_on:
      - gisa-db

  gisa-agenda-3:
    image: gisa-agenda:0.0.1
    container_name: gisa-agenda-3
    restart: always
    ports:
      - "8085:8082"
    networks:
      - apps-network
    depends_on:
      - gisa-db

  gisa-agendamento:
    image: gisa-agendamento:0.0.1
    container_name: gisa-agendamento
    restart: always
    ports:
      - "8083:8083"
    networks:
      - apps-network
    depends_on:
      - gisa-db

  gisa-db:
    image: mysql
    container_name: gisa-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - apps-network
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  apps-network:
    external: 
      name: gisa-network