version: "3.2"

services:

  planos:
    image: gisa-planos:0.0.1-SNAPSHOT
    depends_on:
      - rabbitmq
      - db
    ports:
      - "8080:8080"
    networks:
      - apps-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gisa-plano
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - apps-network

networks:
  apps-network:
    external: 
      name: gisa-network