version: "3.2"

services:

  gisa-auth:
    image: gisa-auth:0.0.1
    restart: always
    ports:
      - "8081:8081"
    networks:
      - apps-network

  gisa-agenda:
    image: gisa-agenda:0.0.1
    restart: always
    ports:
      - "8082:8082"
    networks:
      - apps-network

  gisa-planos:
    image: gisa-planos:0.0.1
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - apps-network

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gisa-plano
    ports:
      - "3307:3306"

networks:
  apps-network:
    external: 
      name: gisa-network